### ISSUE TITLE
Modify score component compositing system to allow reordering

### ISSUE THREAD

**Issue by Matt5sean3** [Harverst/5e-Roper-Droid#5]
Score components (formerly modifiers) need to be changed to allow reordering based on context. Assigning to dotblank since he's the one who rose the issue initially. Mention was made of configuring the order using Java's instanceof feature. Personally, I'm still not sold on that implementation yet but so long as the interface isn't tied to the implementation I won't complain too much.

**Comment by dotblank** [comment]
After some off record discussion, I think the issue is addressable by phases or component buckets. The added flexibility is useful and addresses glitches arising from duplicate entries. Instanceof should not be used if there is an interface or common method that could take its place. The ordering of components can generally be handled with phases and intra-phase malleability.

**Comment by Matt5sean3** [comment]
The phase system is implemented, tested, pulled, and, I believe, addresses this problem well enough.
